#!/usr/bin/env python3
"""Apply the canonical Apple device catalog to the owned Chromium 150 port.

The owned Chromium rebase intentionally keeps its hand-written behavioral
patches separate from generated data. This overlay replaces the provisional
five-row tuple code after the owned patchset is applied and generates the final
C++ catalog from runtime/apple-device-tuples.json.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import os
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = PROJECT_ROOT / "runtime" / "apple-device-tuples.json"
CATALOG_LOADER_PATH = PROJECT_ROOT / "scripts" / "apply-runtime-device-tuples.py"

LOADER_SPEC = importlib.util.spec_from_file_location(
    "neantik_legacy_tuple_catalog",
    CATALOG_LOADER_PATH,
)
assert LOADER_SPEC and LOADER_SPEC.loader
CATALOG_LOADER = importlib.util.module_from_spec(LOADER_SPEC)
sys.modules[LOADER_SPEC.name] = CATALOG_LOADER
LOADER_SPEC.loader.exec_module(CATALOG_LOADER)


HEADER_PATH = "components/ungoogled/neantik_apple_device_tuples.h"
PREIMAGE_SHA256 = {
    "third_party/blink/renderer/core/frame/navigator_concurrent_hardware.cc":
        "0c71caabd085e8ec7d976790284a4b8f144ea8fce6fb17996018a1490264468a",
    "third_party/blink/renderer/core/frame/navigator_device_memory.cc":
        "53a00115a73944d7dec9d4ef9c52ad422c508843e43fa5fbcf2db037bb10d63f",
    "third_party/blink/renderer/core/frame/screen.cc":
        "cec3eefab518188c2bb33870e588e409b982482cf02637cbec8df308838b1c85",
    "third_party/blink/renderer/core/frame/local_dom_window.cc":
        "4631b8862275ba11299bc8ac4be63eb7ae98efe45db2a88ad1cb2c4aef852e9c",
    "third_party/blink/renderer/modules/webgl/webgl_rendering_context_base.cc":
        "603cc2836df7403b0dab8471e8cccdf55ef20c252fc67f3262c8939fb578c0bf",
    "components/embedder_support/user_agent_utils.cc":
        "a4317b2cab28c12f9902ad5cf246d64f7a5dfcfd4dd8f752c643e82ca8e5d5f3",
    "components/embedder_support/BUILD.gn":
        "355120ca227322e7c2c4a2691c8573c2e7b56a0d4c8f8c34b93286a373e4ee38",
}

# Filled from a clean Chromium 150 source pair after the owned patchset and
# this deterministic transform. The script refuses to write unless every
# rendered postimage matches these reviewed digests.
POSTIMAGE_SHA256 = {
    HEADER_PATH:
        "3ef1b5bf96166edcde85177ba4ba14fac9aabf724cb8cb0e14c1076b0648214b",
    "third_party/blink/renderer/core/frame/navigator_concurrent_hardware.cc":
        "ebc2b259e2fc467733904e2eac27621a2e2cd0a415934f94ab1739ee27f0d5aa",
    "third_party/blink/renderer/core/frame/navigator_device_memory.cc":
        "c627f44995fb92e3db4ba43eb75bd91fd53defa8f59f8a18a0b9ce8153d38a8a",
    "third_party/blink/renderer/core/frame/screen.cc":
        "60f1378ba5252765852093b4f288cf1b09d701169f6f12ebf4e379aea7e23429",
    "third_party/blink/renderer/core/frame/local_dom_window.cc":
        "c24ba09b3a1f76baea12df380dd63bf729b5232bd48c128a5f6efa2358247b06",
    "third_party/blink/renderer/modules/webgl/webgl_rendering_context_base.cc":
        "bfc8495a33bc70da13a65883d23cfdce5e03069793a2f8fb9880f1902981bc45",
    "components/embedder_support/user_agent_utils.cc":
        "989eb7bd73fc11f4df1bed9ef37b39e39fc22f5727e7a9ef5477e7c54419eb2f",
    "components/embedder_support/BUILD.gn":
        "1c37df24e83fae9ae7a04c6e12ce830d54d01f5a2cdc045a960aaf3f7418ddac",
}


class OwnedDeviceTupleError(ValueError):
    pass


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def replace_once(text: str, before: str, after: str, *, label: str) -> str:
    count = text.count(before)
    if count != 1:
        raise OwnedDeviceTupleError(
            f"{label}: expected one exact preimage, found {count}"
        )
    return text.replace(before, after, 1)


def render_header(tuples: list[object]) -> str:
    rows: list[str] = []
    for item in tuples:
        rows.append(
            "    {"
            f'"{item.id}", "{item.gpu_model}", '
            f"{item.hardware_concurrency}, {item.physical_memory_gb}, "
            f"{item.web_device_memory_gb}, "
            f"{item.screen_width}, {item.screen_height}, "
            f"{item.available_width}, {item.available_height}, "
            f"{item.color_depth}, {item.device_scale_factor}, "
            f'"{item.platform_version}"'
            "},"
        )
    return (
        "// Generated by apply-owned-runtime-device-tuples.py.\n"
        "// Source: runtime/apple-device-tuples.json. Do not edit by hand.\n"
        "#ifndef COMPONENTS_UNGOOGLED_NEANTIK_APPLE_DEVICE_TUPLES_H_\n"
        "#define COMPONENTS_UNGOOGLED_NEANTIK_APPLE_DEVICE_TUPLES_H_\n\n"
        "#include <cstddef>\n"
        "#include <cstdint>\n\n"
        "namespace ungoogled::nevision {\n\n"
        "struct AppleDeviceTuple {\n"
        "  const char* id;\n"
        "  const char* gpu_model;\n"
        "  unsigned hardware_concurrency;\n"
        "  unsigned physical_memory_gb;\n"
        "  unsigned web_device_memory_gb;\n"
        "  int screen_width;\n"
        "  int screen_height;\n"
        "  int available_width;\n"
        "  int available_height;\n"
        "  unsigned color_depth;\n"
        "  double device_scale_factor;\n"
        "  const char* platform_version;\n"
        "};\n\n"
        "inline constexpr AppleDeviceTuple kAppleDeviceTuples[] = {\n"
        + "\n".join(rows)
        + "\n};\n\n"
        "inline constexpr size_t kAppleDeviceTupleCount =\n"
        "    sizeof(kAppleDeviceTuples) / sizeof(kAppleDeviceTuples[0]);\n\n"
        "inline const AppleDeviceTuple& GetAppleDeviceTuple(uint32_t seed) {\n"
        "  return kAppleDeviceTuples[seed % kAppleDeviceTupleCount];\n"
        "}\n\n"
        "}  // namespace ungoogled::nevision\n\n"
        "#endif  // COMPONENTS_UNGOOGLED_NEANTIK_APPLE_DEVICE_TUPLES_H_\n"
    )


def transform_hardware(text: str) -> str:
    text = replace_once(
        text,
        '#include "components/ungoogled/nevision_fingerprint.h"\n',
        '#include "components/ungoogled/neantik_apple_device_tuples.h"\n'
        '#include "components/ungoogled/nevision_fingerprint.h"\n',
        label="hardware include",
    )
    return replace_once(
        text,
        "  if (ungoogled::nevision::GetProfileSeed().has_value()) {\n"
        "    constexpr unsigned kAppleSiliconHardwareConcurrency[] = {8, 10, 8, 12, 12};\n"
        "    return kAppleSiliconHardwareConcurrency[ungoogled::nevision::GetProfileByte(\n"
        "        \"apple-device-tuple\", 0, (sizeof(kAppleSiliconHardwareConcurrency) / sizeof(kAppleSiliconHardwareConcurrency[0])))];\n"
        "  }\n",
        "  if (const auto seed = ungoogled::nevision::GetProfileSeed()) {\n"
        "    return ungoogled::nevision::GetAppleDeviceTuple(*seed)\n"
        "        .hardware_concurrency;\n"
        "  }\n",
        label="hardware tuple",
    )


def transform_memory(text: str) -> str:
    text = replace_once(
        text,
        '#include "components/ungoogled/nevision_fingerprint.h"\n',
        '#include "components/ungoogled/neantik_apple_device_tuples.h"\n'
        '#include "components/ungoogled/nevision_fingerprint.h"\n',
        label="memory include",
    )
    return replace_once(
        text,
        "  if (ungoogled::nevision::GetProfileSeed().has_value()) {\n"
        "    constexpr float kAppleSiliconWebDeviceMemory[] = {8.0f, 8.0f, 8.0f, 8.0f, 8.0f};\n"
        "    return kAppleSiliconWebDeviceMemory[ungoogled::nevision::GetProfileByte(\n"
        "        \"apple-device-tuple\", 0, (sizeof(kAppleSiliconWebDeviceMemory) / sizeof(kAppleSiliconWebDeviceMemory[0])))];\n"
        "  }\n",
        "  if (const auto seed = ungoogled::nevision::GetProfileSeed()) {\n"
        "    return ungoogled::nevision::GetAppleDeviceTuple(*seed)\n"
        "        .web_device_memory_gb;\n"
        "  }\n",
        label="memory tuple",
    )


def transform_screen(text: str) -> str:
    text = replace_once(
        text,
        '#include "components/ungoogled/nevision_fingerprint.h"\n',
        '#include "components/ungoogled/neantik_apple_device_tuples.h"\n'
        '#include "components/ungoogled/nevision_fingerprint.h"\n',
        label="screen include",
    )
    text = replace_once(
        text,
        "struct NeAntikAppleScreenTuple {\n"
        "  int width;\n"
        "  int height;\n"
        "  int avail_width;\n"
        "  int avail_height;\n"
        "};\n\n"
        "const NeAntikAppleScreenTuple* GetNeAntikAppleScreenTuple() {\n"
        "  if (!ungoogled::nevision::GetProfileSeed().has_value()) {\n"
        "    return nullptr;\n"
        "  }\n"
        "  static constexpr NeAntikAppleScreenTuple kTuples[] = {\n"
        "      {1280, 800, 1280, 775},\n"
        "      {1512, 982, 1512, 957},\n"
        "      {1280, 832, 1280, 807},\n"
        "      {1728, 1117, 1728, 1092},\n"
        "      {1512, 982, 1512, 957},\n"
        "  };\n"
        "  return &kTuples[ungoogled::nevision::GetProfileByte(\n"
        "      \"apple-device-tuple\", 0, (sizeof(kTuples) / sizeof(kTuples[0])))];\n"
        "}\n",
        "const ungoogled::nevision::AppleDeviceTuple*\n"
        "GetNeAntikAppleScreenTuple() {\n"
        "  const auto seed = ungoogled::nevision::GetProfileSeed();\n"
        "  return seed ? &ungoogled::nevision::GetAppleDeviceTuple(*seed)\n"
        "              : nullptr;\n"
        "}\n",
        label="screen helper",
    )
    text = replace_once(
        text,
        "  if (!DomWindow()) {\n"
        "    return unknown_color_depth;\n"
        "  }\n"
        "  return GetScreenInfo().depth == 0\n",
        "  if (!DomWindow()) {\n"
        "    return unknown_color_depth;\n"
        "  }\n"
        "  if (const auto* tuple = GetNeAntikAppleScreenTuple()) {\n"
        "    return tuple->color_depth;\n"
        "  }\n"
        "  return GetScreenInfo().depth == 0\n",
        label="screen color depth",
    )
    return replace_once(
        text,
        "  if (const NeAntikAppleScreenTuple* tuple = GetNeAntikAppleScreenTuple()) {\n"
        "    return gfx::Rect(0, 0, available ? tuple->avail_width : tuple->width,\n"
        "                     available ? tuple->avail_height : tuple->height);\n"
        "  }\n",
        "  if (const auto* tuple = GetNeAntikAppleScreenTuple()) {\n"
        "    return gfx::Rect(\n"
        "        0, 0,\n"
        "        available ? tuple->available_width : tuple->screen_width,\n"
        "        available ? tuple->available_height : tuple->screen_height);\n"
        "  }\n",
        label="screen rect",
    )


def transform_scale(text: str) -> str:
    text = replace_once(
        text,
        '#include "components/ungoogled/nevision_fingerprint.h"\n',
        '#include "components/ungoogled/neantik_apple_device_tuples.h"\n'
        '#include "components/ungoogled/nevision_fingerprint.h"\n',
        label="scale include",
    )
    return replace_once(
        text,
        "  if (ungoogled::nevision::GetProfileSeed().has_value()) {\n"
        "    return 2.0;\n"
        "  }\n",
        "  if (const auto seed = ungoogled::nevision::GetProfileSeed()) {\n"
        "    return ungoogled::nevision::GetAppleDeviceTuple(*seed)\n"
        "        .device_scale_factor;\n"
        "  }\n",
        label="device scale",
    )


def transform_webgl(text: str) -> str:
    text = replace_once(
        text,
        '#include "components/ungoogled/nevision_fingerprint.h"\n',
        '#include "components/ungoogled/neantik_apple_device_tuples.h"\n'
        '#include "components/ungoogled/nevision_fingerprint.h"\n',
        label="webgl include",
    )
    text = replace_once(
        text,
        "      if (ExtensionEnabled(kWebGLDebugRendererInfoName)) {\n"
        "        if (base::FeatureList::IsEnabled(blink::features::kSpoofWebGLInfo))\n"
        "          return WebGLAny(script_state, String(blink::features::kSpoofWebGLRendererParam.Get()));\n"
        "        return WebGLAny(script_state,\n"
        "                        String(ContextGL()->GetString(GL_RENDERER)));\n"
        "      }\n",
        "      if (ExtensionEnabled(kWebGLDebugRendererInfoName)) {\n"
        "        if (const auto seed = ungoogled::nevision::GetProfileSeed()) {\n"
        "          const auto& tuple =\n"
        "              ungoogled::nevision::GetAppleDeviceTuple(*seed);\n"
        "          return WebGLAny(\n"
        "              script_state,\n"
        "              String::Format(\n"
        "                  \"ANGLE (Apple, ANGLE Metal Renderer: Apple %s, \"\n"
        "                  \"Unspecified Version)\",\n"
        "                  tuple.gpu_model));\n"
        "        }\n"
        "        if (base::FeatureList::IsEnabled(blink::features::kSpoofWebGLInfo))\n"
        "          return WebGLAny(script_state, String(blink::features::kSpoofWebGLRendererParam.Get()));\n"
        "        return WebGLAny(script_state,\n"
        "                        String(ContextGL()->GetString(GL_RENDERER)));\n"
        "      }\n",
        label="webgl renderer",
    )
    return replace_once(
        text,
        "      if (ExtensionEnabled(kWebGLDebugRendererInfoName)) {\n"
        "        if (base::FeatureList::IsEnabled(blink::features::kSpoofWebGLInfo))\n"
        "          return WebGLAny(script_state, String(blink::features::kSpoofWebGLVendorParam.Get()));\n"
        "        return WebGLAny(script_state,\n"
        "                        String(ContextGL()->GetString(GL_VENDOR)));\n"
        "      }\n",
        "      if (ExtensionEnabled(kWebGLDebugRendererInfoName)) {\n"
        "        if (ungoogled::nevision::GetProfileSeed()) {\n"
        "          return WebGLAny(script_state, String(\"Google Inc. (Apple)\"));\n"
        "        }\n"
        "        if (base::FeatureList::IsEnabled(blink::features::kSpoofWebGLInfo))\n"
        "          return WebGLAny(script_state, String(blink::features::kSpoofWebGLVendorParam.Get()));\n"
        "        return WebGLAny(script_state,\n"
        "                        String(ContextGL()->GetString(GL_VENDOR)));\n"
        "      }\n",
        label="webgl vendor",
    )


def transform_user_agent(text: str) -> str:
    text = replace_once(
        text,
        '#include "components/embedder_support/switches.h"\n',
        '#include "components/embedder_support/switches.h"\n'
        '#include "components/ungoogled/neantik_apple_device_tuples.h"\n'
        '#include "components/ungoogled/nevision_fingerprint.h"\n',
        label="user agent include",
    )
    return replace_once(
        text,
        "#else\n\n"
        "  int32_t major, minor, bugfix = 0;\n",
        "#else\n\n"
        "#if BUILDFLAG(IS_MAC)\n"
        "  if (const auto seed = ungoogled::nevision::GetProfileSeed()) {\n"
        "    return ungoogled::nevision::GetAppleDeviceTuple(*seed)\n"
        "        .platform_version;\n"
        "  }\n"
        "#endif\n\n"
        "  int32_t major, minor, bugfix = 0;\n",
        label="user agent platform version",
    )


def transform_user_agent_build(text: str) -> str:
    return replace_once(
        text,
        '    "//components/policy/core/common",\n'
        '    "//components/prefs",\n'
        '    "//components/version_info",\n',
        '    "//components/policy/core/common",\n'
        '    "//components/prefs",\n'
        '    "//components/ungoogled:ungoogled_switches",\n'
        '    "//components/version_info",\n',
        label="user agent dependency",
    )


TRANSFORMS = {
    "third_party/blink/renderer/core/frame/navigator_concurrent_hardware.cc":
        transform_hardware,
    "third_party/blink/renderer/core/frame/navigator_device_memory.cc":
        transform_memory,
    "third_party/blink/renderer/core/frame/screen.cc": transform_screen,
    "third_party/blink/renderer/core/frame/local_dom_window.cc":
        transform_scale,
    "third_party/blink/renderer/modules/webgl/webgl_rendering_context_base.cc":
        transform_webgl,
    "components/embedder_support/user_agent_utils.cc": transform_user_agent,
    "components/embedder_support/BUILD.gn": transform_user_agent_build,
}


def atomic_write(path: Path, data: bytes, *, mode: int) -> None:
    temporary = path.with_name(f".{path.name}.neantik-tuples")
    temporary.write_bytes(data)
    os.chmod(temporary, mode)
    os.replace(temporary, path)


def rendered_postimages(source_root: Path) -> dict[str, bytes]:
    tuples = CATALOG_LOADER.load_device_tuples(CATALOG_PATH)
    rendered = {HEADER_PATH: render_header(tuples).encode("utf-8")}
    for relative, transform in TRANSFORMS.items():
        path = source_root / relative
        try:
            original = path.read_bytes()
        except OSError as error:
            raise OwnedDeviceTupleError(
                f"missing Chromium source file: {relative}"
            ) from error
        actual = sha256_bytes(original)
        expected_postimage = POSTIMAGE_SHA256[relative]
        if actual == expected_postimage:
            rendered[relative] = original
            continue
        if actual != PREIMAGE_SHA256[relative]:
            raise OwnedDeviceTupleError(
                f"{relative}: unexpected preimage SHA-256 {actual}"
            )
        try:
            rendered[relative] = transform(original.decode("utf-8")).encode(
                "utf-8"
            )
        except UnicodeDecodeError as error:
            raise OwnedDeviceTupleError(
                f"{relative}: source is not UTF-8"
            ) from error
    return rendered


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Generate and apply the canonical NeAntik Apple tuple overlay "
            "to an owned Chromium 150 source root."
        )
    )
    parser.add_argument("source_root", type=Path)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--show-postimages", action="store_true")
    args = parser.parse_args()
    source_root = args.source_root.resolve()
    try:
        rendered = rendered_postimages(source_root)
    except (OwnedDeviceTupleError, CATALOG_LOADER.DeviceTupleCatalogError) as error:
        print(f"Owned device tuple overlay failed: {error}", file=sys.stderr)
        return 65

    actual_postimages = {
        relative: sha256_bytes(data)
        for relative, data in rendered.items()
    }
    if args.show_postimages:
        for relative in sorted(actual_postimages):
            print(f"{relative} {actual_postimages[relative]}")
        return 0

    mismatches = [
        f"{relative}: expected {POSTIMAGE_SHA256[relative]}, "
        f"rendered {actual_postimages[relative]}"
        for relative in sorted(actual_postimages)
        if actual_postimages[relative] != POSTIMAGE_SHA256[relative]
    ]
    if mismatches:
        print(
            "Owned device tuple overlay postimages are not reviewed:\n"
            + "\n".join(mismatches),
            file=sys.stderr,
        )
        return 65

    if args.check:
        for relative, data in rendered.items():
            path = source_root / relative
            if not path.is_file() or path.read_bytes() != data:
                print(
                    f"Owned device tuple overlay is not applied: {relative}",
                    file=sys.stderr,
                )
                return 65
        print(
            "Owned Chromium Apple device tuple overlay verified: "
            f"{len(rendered)} postimages."
        )
        return 0

    for relative, data in rendered.items():
        path = source_root / relative
        if path.is_file() and path.read_bytes() == data:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        mode = path.stat().st_mode if path.exists() else 0o644
        atomic_write(path, data, mode=mode)
        print(f"APPLY {relative}")
    print(
        "Owned Chromium Apple device tuple overlay applied: "
        f"{len(rendered)} postimages."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
