#!/usr/bin/env python3
"""Compare exact M156 inventories; only source-derived CPython caches may vary.

This does not qualify a runtime. The caller must authenticate both full
inventories and bind a fresh terminal build/source/binary receipt separately.
No source is imported or executed to validate a generated bytecode cache.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import stat
import struct
import subprocess
from pathlib import Path
from typing import Any
from chromium_15612_receipt_projection import VERSION, COMMIT, TREE

HASH = re.compile(r"[0-9a-f]{64}\Z")
CACHE = re.compile(r"(.+)/__pycache__/([^/]+)\.cpython-314\.pyc\Z")

class M156CacheError(ValueError):
    pass


def need(ok: bool, message: str) -> None:
    if not ok:
        raise M156CacheError(message)


def relative_path(value: Any) -> str:
    need(isinstance(value, str) and 0 < len(value) <= 4096 and
         not value.startswith('/') and '\\' not in value and '\x00' not in value and
         all(part not in {'', '.', '..'} for part in value.split('/')), 'Unsafe source inventory path')
    return value


def inventory(document: dict[str, Any]) -> dict[str, dict[str, Any]]:
    need(isinstance(document, dict) and type(document.get('schemaVersion')) is int and
         document['schemaVersion'] == 1 and document.get('recordType') == 'chromium-source-snapshot' and
         document.get('targetChromiumVersion') == VERSION and
         document.get('officialChromiumBase') == {'commit': COMMIT, 'tree': TREE} and
         document.get('releaseReady') is False, 'M156 inventory identity mismatch')
    entries, deleted = document.get('entries'), document.get('deletedPaths')
    need(isinstance(entries, list) and 0 < len(entries) <= 2_000_000 and
         type(document.get('sourceFileCount')) is int and len(entries) == document['sourceFileCount'] and
         isinstance(deleted, list) and len(deleted) <= 2_000_000 and
         type(document.get('deletedPathCount')) is int and len(deleted) == document['deletedPathCount'], 'M156 inventory count mismatch')
    need(deleted == sorted(set(relative_path(n) for n in deleted)), 'M156 deleted paths not unique and sorted')
    result = {}
    previous = ''
    for item in entries:
        need(isinstance(item, dict), 'Invalid source record')
        name = relative_path(item.get('path'))
        need(name > previous and name not in result, 'M156 source records not unique and sorted')
        previous = name
        kind = item.get('kind')
        keys = {'kind', 'path', 'mode', 'sizeBytes', 'sha256'} if kind == 'file' else {'kind', 'path', 'mode', 'targetLength', 'targetSHA256'}
        need(kind in {'file', 'symlink'} and set(item) == keys, 'Unknown source record fields or type')
        size_key, hash_key = ('sizeBytes', 'sha256') if kind == 'file' else ('targetLength', 'targetSHA256')
        need(type(item['mode']) is int and 0 <= item['mode'] <= 0o7777 and
             type(item[size_key]) is int and 0 <= item[size_key] <= 64*1024**3 and
             isinstance(item[hash_key], str) and HASH.fullmatch(item[hash_key]) is not None, 'Invalid source record identity')
        result[name] = item
    need(not set(result).intersection(deleted), 'Source path simultaneously present and deleted')
    return result


def compare_inventories(before: dict[str, Any], after: dict[str, Any]) -> list[dict[str, Any]]:
    """Every non-cache source/deletion/arg change is a hard failure."""
    old, new = inventory(before), inventory(after)
    need(before.get('argsGN') == after.get('argsGN') and isinstance(before.get('argsGN'), dict) and
         set(before['argsGN']) == {'relativePath', 'sha256'} and
         before['argsGN']['relativePath'] == 'out/NeAntikM156Qualified20261009/args.gn' and
         before['argsGN']['sha256'] == 'b32623308042c6b3b86f14ce9635ccc9abdc290148ce596c1e4f4a43ffde9a01', 'M156 build args changed')
    need(before['deletedPaths'] == after['deletedPaths'], 'M156 deleted paths changed during build')
    caches = []
    for name in sorted(set(old) | set(new)):
        a, b = old.get(name), new.get(name)
        if a == b:
            continue
        match = CACHE.fullmatch(name)
        need(match is not None and b is not None and b['kind'] == 'file' and
             b['sizeBytes'] <= 4*1024*1024 and b['mode'] == 0o644 and
             (a is None or (a['kind'] == 'file' and a['mode'] == b['mode'])), 'Unexpected M156 source delta')
        source = relative_path(match[1] + '/' + match[2] + '.py')
        need(source in old and old[source]['kind'] == 'file' and old[source] == new.get(source), 'Cache source absent or changed')
        caches.append({'cache': name, 'source': source, 'cacheSHA256': b['sha256'],
                       'sourceSHA256': old[source]['sha256'], 'cacheBytes': b['sizeBytes']})
    return caches


def read_source_record(root: Path, name: str, maximum: int) -> tuple[bytes, os.stat_result]:
    """FD-relative no-follow reads; no symlink ancestor or unbounded growth."""
    need(root.is_absolute() and not root.is_symlink(), 'Real absolute source root required')
    parts = relative_path(name).split('/')
    directory = os.open(root, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)
    try:
        for part in parts[:-1]:
            next_fd = os.open(part, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW, dir_fd=directory)
            os.close(directory)
            directory = next_fd
        fd = os.open(parts[-1], os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK, dir_fd=directory)
        try:
            before = os.fstat(fd)
            need(stat.S_ISREG(before.st_mode) and before.st_nlink == 1 and
                 before.st_uid == os.getuid() and 0 <= before.st_size <= maximum, 'Unsafe or oversized source/cache file')
            data = bytearray()
            while len(data) <= before.st_size:
                chunk = os.read(fd, min(65536, before.st_size + 1 - len(data)))
                if not chunk:
                    break
                data.extend(chunk)
            after, current = os.fstat(fd), os.stat(parts[-1], dir_fd=directory, follow_symlinks=False)
            identity = lambda s: (s.st_dev, s.st_ino, s.st_size, s.st_mtime_ns, s.st_ctime_ns)
            need(len(data) == before.st_size and identity(before) == identity(after) == identity(current) and
                 stat.S_ISREG(current.st_mode), 'Source/cache file changed during read')
            return bytes(data), before
        finally:
            os.close(fd)
    finally:
        os.close(directory)


def read_source_file(root: Path, name: str, maximum: int) -> bytes:
    return read_source_record(root, name, maximum)[0]


class MarshalPreflight:
    """Bound CPython3.14 code-cache allocation before marshal creates objects.

    Independent structural reader, based on the format in CPython v3.14.4
    Python/marshal.c. Reject unknown tags, incomplete/cyclic references,
    non-compiler containers and oversized counts before native decoding.
    https://github.com/python/cpython/blob/v3.14.4/Python/marshal.c
    """
    def __init__(self, body: bytes):
        need(0 < len(body) <= 4*1024*1024, 'Invalid marshal body size')
        self.body, self.offset, self.nodes, self.elements = body, 0, 0, 0
        self.refs: list[tuple[str, int] | None] = []
        self.allocation_charge = 0

    def charge(self, size: int) -> None:
        # Conservative structural budget, not a claimed process RSS limit.
        # Charge native per-code copies even when marshal references reuse
        # one bytes/tuple object. CPython code objects own adaptive bytecode.
        self.allocation_charge += size
        need(self.allocation_charge <= 64*1024*1024, 'Marshal allocation budget exceeded')

    def take(self, count: int) -> bytes:
        need(0 <= count <= len(self.body)-self.offset, 'Truncated marshal field')
        start = self.offset
        self.offset += count
        return self.body[start:self.offset]

    def integer(self) -> int:
        return struct.unpack('<i', self.take(4))[0]

    def count(self) -> int:
        n = self.integer()
        need(0 <= n <= 100_000, 'Marshal allocation count exceeded')
        return n

    def object(self, depth: int = 0) -> tuple[str, int]:
        self.nodes += 1
        self.charge(512)
        size = 0
        need(depth <= 64 and self.nodes <= 100_000, 'Marshal object budget exceeded')
        tag = self.take(1)[0]
        referenced, tag = bool(tag & 0x80), chr(tag & 0x7f)
        slot = None
        if referenced:
            need(tag not in '0NFTS.r', 'Invalid reference flag')
            slot = len(self.refs)
            self.refs.append(None)
        if tag in 'NFTS.':
            kind = 'scalar'
        elif tag == 'r':
            index = self.integer()
            need(0 <= index < len(self.refs) and self.refs[index] is not None,
                 'Invalid or cyclic marshal reference')
            kind, size = self.refs[index]
        elif tag in 'iIgy':
            self.take({'i':4, 'I':8, 'g':8, 'y':16}[tag])
            kind = 'scalar'
        elif tag == 'l':
            digits = self.integer()
            need(abs(digits) <= 100_000, 'Marshal long allocation exceeded')
            self.charge(abs(digits)*4)
            self.take(abs(digits)*2)
            kind = 'scalar'
        elif tag in 'sutaAzZ':
            size = self.take(1)[0] if tag in 'zZ' else self.integer()
            need(0 <= size <= 4*1024*1024, 'Marshal string allocation exceeded')
            self.charge(size*4)
            self.take(size)
            kind = 'bytes' if tag == 's' else 'str'
        elif tag in '()>':
            count = self.take(1)[0] if tag == ')' else self.count()
            self.elements += count
            need(self.elements <= 100_000 and count <= len(self.body)-self.offset,
                 'Marshal element budget exceeded')
            self.charge(count*16)
            size = count
            for _ in range(count):
                self.object(depth+1)
            kind = 'tuple' if tag in '()' else 'frozenset'
        elif tag == ':':
            for _ in range(3):
                self.object(depth+1)
            kind = 'slice'
        elif tag == 'c':
            for _ in range(4):
                self.count()  # argument counts and stack size
            need(0 <= self.integer() <= 0x7fffffff, 'Invalid marshal code flags')
            for expected in ('bytes','tuple','tuple','tuple','bytes','str','str','str'):
                field, length = self.object(depth+1)
                need(field == expected, 'Invalid marshal code field type')
                self.charge(length*(64 if field == 'tuple' else 8))
            need(self.integer() >= 0, 'Invalid first source line')
            for _ in range(2):
                field, length = self.object(depth+1)
                need(field == 'bytes', 'Invalid marshal code tables')
                self.charge(length*8)
            kind = 'code'
        else:
            raise M156CacheError('Unsupported compiler marshal tag')
        if slot is not None:
            self.refs[slot] = (kind, size)
        return kind, size

    def validate(self) -> None:
        need(self.object()[0] == 'code' and self.offset == len(self.body),
             'Marshal root or trailing bytes invalid')


# Runs under the reviewed producer minor version in an isolated process.
# compile() creates a code object only. exec(), imports of source, and source
# side effects are forbidden. Complete marshal body consumption is required.
CACHE_CHECK_PROGRAM = r'''
import importlib.util, io, marshal, struct, sys, types, json, os
need=lambda ok: None if ok else (_ for _ in ()).throw(ValueError('Generated cache derivation failed'))
need(sys.version_info[:2] == (3, 14))
item=json.loads(sys.stdin.read())
raw=bytes.fromhex(item['cacheHex']);source=bytes.fromhex(item['sourceHex'])
need(len(raw)>16 and raw[:4]==importlib.util.MAGIC_NUMBER)
need(struct.unpack('<I',raw[4:8])[0]==0)
need(struct.unpack('<I',raw[8:12])[0]==item['sourceTimestamp'])
need(struct.unpack('<I',raw[12:16])[0]==len(source))
stream=io.BytesIO(raw[16:]);code=marshal.load(stream)
need(stream.tell()==len(raw)-16 and isinstance(code,types.CodeType))
filename=code.co_filename
need(type(filename) is str and len(filename)<=4096 and os.path.isabs(filename))
need(filename.startswith(item['sourceRoot']+os.sep) and
     os.path.normpath(filename)==item['sourceFilename'])
operations=0
def constant(a,depth=0):
 global operations
 operations+=1;need(depth<=64 and operations<=100000)
 t=type(a)
 if t is types.CodeType:return ('code',code_value(a,depth+1))
 if t is float:return ('float',struct.pack('>d',a))
 if t is complex:return ('complex',struct.pack('>dd',a.real,a.imag))
 if t is tuple:return ('tuple',tuple(constant(x,depth+1) for x in a))
 if t is frozenset:
  counts={}
  for x in a:
   key=constant(x,depth+1);counts[key]=counts.get(key,0)+1
  return ('frozenset',frozenset(counts.items()))
 if t is slice:return ('slice',constant(a.start,depth+1),constant(a.stop,depth+1),constant(a.step,depth+1))
 need(t in (type(None),bool,int,str,bytes) or a is Ellipsis)
 return (t.__name__,a)
def code_value(a,depth):
 need(depth<=64)
 fields=('co_argcount','co_posonlyargcount','co_kwonlyargcount','co_nlocals','co_stacksize','co_flags','co_code','co_names','co_varnames','co_filename','co_name','co_qualname','co_firstlineno','co_linetable','co_exceptiontable','co_freevars','co_cellvars')
 return tuple(getattr(a,k) for k in fields)+(tuple(constant(x,depth+1) for x in a.co_consts),)
need(code_value(code,0)==code_value(compile(source,filename,'exec',dont_inherit=True,optimize=0),0))
print('verified-source-derived-cache')
'''


def verify_cache(root: Path, record: dict[str, Any], python: Path, *, python_sha256: str) -> None:
    need(set(record) == {'cache', 'source', 'cacheSHA256', 'sourceSHA256', 'cacheBytes'}, 'Cache record schema mismatch')
    match = CACHE.fullmatch(relative_path(record['cache']))
    need(match is not None and relative_path(record['source']) == match[1] + '/' + match[2] + '.py',
         'Cache source correspondence mismatch')
    for field in ('cacheSHA256', 'sourceSHA256'):
        need(isinstance(record[field], str) and HASH.fullmatch(record[field]) is not None, 'Invalid cache digest')
    need(type(record['cacheBytes']) is int and 0 <= record['cacheBytes'] <= 4*1024*1024, 'Invalid cache size')
    raw = read_source_file(root, record['cache'], 4*1024*1024)
    source, source_stat = read_source_record(root, record['source'], 4*1024*1024)
    need(len(raw) == record['cacheBytes'] and hashlib.sha256(raw).hexdigest() == record['cacheSHA256'] and
         hashlib.sha256(source).hexdigest() == record['sourceSHA256'], 'Cache/source digest mismatch')
    MarshalPreflight(raw[16:]).validate()
    source_path = root / record['source']
    # The caller pins interpreter/tool bytes in its native toolchain receipt.
    # This function neither installs nor resolves a moving Python runtime.
    need(python.is_absolute() and python.is_file() and isinstance(python_sha256, str) and
         HASH.fullmatch(python_sha256) is not None, 'Reviewed Python interpreter required')
    interpreter = python.resolve(strict=True)
    digest = hashlib.sha256()
    with interpreter.open('rb') as stream:
        for block in iter(lambda: stream.read(1024*1024), b''):
            digest.update(block)
    need(digest.hexdigest() == python_sha256, 'Reviewed Python interpreter changed')
    item = {'cacheHex': raw.hex(), 'sourceHex': source.hex(),
            'sourceTimestamp': int(source_stat.st_mtime) & 0xffffffff,
            'sourceFilename': str(source_path), 'sourceRoot': str(root)}
    result = subprocess.run([str(interpreter), '-I', '-S', '-B', '-c', CACHE_CHECK_PROGRAM],
                            input=json.dumps(item), stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                            text=True, timeout=15, check=False)
    need(result.returncode == 0 and result.stdout.strip() == 'verified-source-derived-cache', 'Generated cache derivation failed')
