#!/usr/bin/env python3
from __future__ import annotations

import argparse
import importlib.util
import shlex
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
PREFLIGHT_PATH = PROJECT_ROOT / "scripts" / "preflight-runtime-rebase-150.py"
SPEC = importlib.util.spec_from_file_location("preflight_runtime_rebase_150", PREFLIGHT_PATH)
assert SPEC and SPEC.loader
PREFLIGHT = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = PREFLIGHT
SPEC.loader.exec_module(PREFLIGHT)


class BootstrapError(ValueError):
    pass


def q(value: object) -> str:
    return shlex.quote(str(value))


def build_script(*, project_root: Path, build_root: Path, plan: object) -> str:
    return f"""#!/bin/zsh
set -euo pipefail

# Generated by scripts/generate-runtime-rebase-150-bootstrap.py.
# It prepares a pinned Chromium 150 source workspace only after the same
# preflight gate has already confirmed the target path and free space.
# It never deletes or mutates the preserved Chromium 144 evidence root.

PROJECT_ROOT={q(project_root)}
BUILD_ROOT={q(build_root)}
MAC_REPO={q(plan.mac_repository)}
MAC_COMMIT={q(plan.mac_commit)}
COMMON_REPO={q(plan.common_repository)}
COMMON_TAG={q(plan.common_tag)}
COMMON_COMMIT={q(plan.common_commit)}
COMMON_ROOT="$BUILD_ROOT/ungoogled-chromium"

python3 "$PROJECT_ROOT/scripts/preflight-runtime-rebase-150.py" "$BUILD_ROOT"
python3 "$PROJECT_ROOT/scripts/verify-runtime-security-reference.py"
python3 "$PROJECT_ROOT/scripts/verify-nevision-patchset-manifest.py" --source-evidence

mkdir -p "$(dirname "$BUILD_ROOT")"

if [[ ! -e "$BUILD_ROOT/.git" ]]; then
  git clone "$MAC_REPO" "$BUILD_ROOT"
fi
git -C "$BUILD_ROOT" fetch --tags origin "$MAC_COMMIT" || git -C "$BUILD_ROOT" fetch origin
git -C "$BUILD_ROOT" checkout --detach "$MAC_COMMIT"

if [[ ! -e "$COMMON_ROOT/.git" ]]; then
  git clone "$COMMON_REPO" "$COMMON_ROOT"
fi
git -C "$COMMON_ROOT" fetch --tags origin "$COMMON_TAG"
git -C "$COMMON_ROOT" checkout --detach "$COMMON_COMMIT"

python3 "$PROJECT_ROOT/scripts/preflight-runtime-rebase-150.py" "$BUILD_ROOT"
python3 "$PROJECT_ROOT/scripts/verify-nevision-patchset-manifest.py" --source-evidence

cat <<'NEXT_STEPS'
Chromium 150 source-pair bootstrap is pinned.
Next:
1. Unpack Chromium source into "$BUILD_ROOT/build/src" with the approved Chromium 150 prepare/build flow.
2. Run scripts/preflight-runtime-rebase-150.py "$BUILD_ROOT" --source-root "$BUILD_ROOT/build/src".
3. Port release-required groups from runtime/nevision-patches/series.json against "$BUILD_ROOT/build/src".
4. Record patchSHA256 and postimageSHA256 for every ported group.
5. Run scripts/verify-nevision-patchset-manifest.py --source-evidence --release --source-root "$BUILD_ROOT/build/src".
6. Build ARM64 Metal runtime, regenerate source lock, notices, SBOM, and GUI A -> B -> A evidence.
NEXT_STEPS
"""


def generate(
    *,
    project_root: Path,
    build_root: Path,
    output: Path,
    free_gib: int | None = None,
) -> str:
    plan_path = project_root / "runtime" / "chromium-150-rebase-plan.json"
    baseline_path = project_root / "runtime" / "security-baseline.json"
    plan = PREFLIGHT.parse_plan(plan_path)
    preflight = PREFLIGHT.verify(
        plan_path=plan_path,
        baseline_path=baseline_path,
        build_root=build_root,
        free_gib=free_gib,
    )
    script = build_script(project_root=project_root, build_root=build_root, plan=plan)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(script, encoding="utf-8")
    output.chmod(0o755)
    return preflight + f"\nBootstrap script written: {output}"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate a pinned Chromium 150 source-bootstrap script after the NeAntik rebase preflight passes.",
    )
    parser.add_argument(
        "build_root",
        type=Path,
        nargs="?",
        default=Path("/private/tmp/nevision-chromium-150"),
    )
    parser.add_argument("--project-root", type=Path, default=PROJECT_ROOT)
    parser.add_argument(
        "--output",
        type=Path,
        default=PROJECT_ROOT / "dist" / "NeAntik-Chromium-150-bootstrap.sh",
    )
    parser.add_argument(
        "--free-gib",
        type=int,
        default=None,
        help="Test override for the free-space gate; do not use for real release preparation.",
    )
    args = parser.parse_args()

    try:
        print(
            generate(
                project_root=args.project_root.resolve(),
                build_root=args.build_root,
                output=args.output,
                free_gib=args.free_gib,
            )
        )
    except (BootstrapError, PREFLIGHT.RebasePreflightError) as error:
        print(f"Chromium 150 bootstrap generation failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
