#!/bin/bash

set -euo pipefail

usage() {
  echo "Usage: $0 /absolute/path/to/compliance-directory /absolute/path/to/runtime-candidate-lock.json" >&2
}

if [[ $# -ne 2 ||
      "$1" != /* ||
      ! -d "$1" ||
      "$2" != /* ||
      ! -f "$2" ||
      -L "$2" ]]; then
  usage
  exit 64
fi

COMPLIANCE_DIR="$1"
LOCK_FILE="$2"
MANIFEST="$COMPLIANCE_DIR/compliance-manifest.json"
if [[ ! -f "$MANIFEST" ]]; then
  echo "Compliance manifest is missing." >&2
  exit 66
fi

LOCK_FILE="$LOCK_FILE" \
COMPLIANCE_DIR="$COMPLIANCE_DIR" \
MANIFEST="$MANIFEST" \
python3 - <<'PY'
import hashlib
import json
import os
from pathlib import Path

def fail(message: str) -> None:
    raise SystemExit(message)

def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()

root = Path(os.environ["COMPLIANCE_DIR"])
manifest = json.loads(Path(os.environ["MANIFEST"]).read_text(encoding="utf-8"))
lock_path = Path(os.environ["LOCK_FILE"])
lock = json.loads(lock_path.read_text(encoding="utf-8"))

if manifest.get("schemaVersion") != 1:
    fail("Unexpected compliance manifest schema.")
expected_version = lock["fingerprintChromium"]["chromiumVersion"]
if manifest.get("chromiumVersion") != expected_version:
    fail("Compliance Chromium version does not match the source lock.")
if manifest.get("sourceLockSHA256") != sha256(lock_path):
    fail("Compliance source-lock hash does not match.")

notices_meta = manifest.get("notices", {})
spdx_meta = manifest.get("spdx", {})
notices_path = root / str(notices_meta.get("file", ""))
spdx_path = root / str(spdx_meta.get("file", ""))
if not notices_path.is_file() or not spdx_path.is_file():
    fail("Compliance notices or SPDX document is missing.")
if sha256(notices_path) != notices_meta.get("sha256"):
    fail("Compliance notices hash mismatch.")
if sha256(spdx_path) != spdx_meta.get("sha256"):
    fail("Compliance SPDX hash mismatch.")

credits = notices_path.read_text(encoding="utf-8")
entry_count = credits.count('<div class="product">')
if entry_count != notices_meta.get("entryCount") or entry_count < 500:
    fail("Third-party notices coverage is unexpectedly small.")
if "Generated by licenses.py" not in credits:
    fail("Third-party notices are not a Chromium-generated artifact.")

spdx = json.loads(spdx_path.read_text(encoding="utf-8"))
package_count = len(spdx.get("packages", []))
license_count = len(spdx.get("hasExtractedLicensingInfos", []))
if spdx.get("spdxVersion") != "SPDX-2.2":
    fail("Unexpected SPDX version.")
if package_count != spdx_meta.get("packageCount") or package_count < 500:
    fail("SPDX package coverage is unexpectedly small.")
if (
    license_count != spdx_meta.get("extractedLicenseCount")
    or license_count < 500
):
    fail("SPDX extracted-license coverage is unexpectedly small.")
if spdx.get("documentNamespace") != spdx_meta.get("documentNamespace"):
    fail("SPDX namespace does not match the manifest.")
PY

echo "NeAntik runtime compliance artifacts verified."
